### ISSUE TITLE
Unhandled promise regection on missconfigured appservice

### ISSUE THREAD

**Issue by Sorunome** [turt2live/matrix-js-bot-sdk#30]
If an AS is missconfigured this lib throws an unhandled promise rejection as it can't decode JSON:

```
(node:3853) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Intent.<anonymous> (/home/sorunome/repos/mx-puppet-bridge/node_modules/matrix-bot-sdk/lib/appservice/Intent.js:135:41)
    at Generator.throw (<anonymous>)
    at rejected (/home/sorunome/repos/mx-puppet-bridge/node_modules/matrix-bot-sdk/lib/appservice/Intent.js:5:65)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

perhaps handle this?

**Comment by turt2live** [comment]
Which sample code triggers this?

**Comment by Sorunome** [comment]
don't remember anymore and never committed that part, sadly :(
